#include <iostream>
#include <bits/stdc++.h>
using namespace std;

int main()
{
    string str;
    cin >> str;
    if (str == "Monday")
    {
        cout << 5 << endl;
    }
    if (str == "Tuesday")
    {
        cout << 4 << endl;
    }
    if (str == "Wednesday")
    {
        cout << 3 << endl;
    }
    if (str == "Thursday")
    {
        cout << 2 << endl;
    }
    if (str == "Friday")
    {
        cout << 1 << endl;
    }

    return 0;
}
